### ISSUE TITLE
YARP architecture for the human dynamics estimation

### ISSUE THREAD

**Issue by claudia-lat** [robotology-playground/human-dynamics-estimation#1]
I've jotted down a preliminary overview of the YARP modules architecture for the estimation of the dynamics in humans.

![hde_yarp_architecture](https://cloud.githubusercontent.com/assets/10923418/23015323/a355a2be-f432-11e6-9ff2-16b0e6440018.png)

**Comment by traversaro** [comment]
cc @diegoferigo @martalorenzini To understand where we can include the visualization.

**Comment by claudia-lat** [comment]
For external wrenches we would like to have:
- the value
- the frame with respect to it's expressed
- the link on which it's applied

**Comment by claudia-lat** [comment]
For the module related to the `human kinematics`, the inputs are:
- the raw data coming from Xsens acquisition
- a generic template for the human model

As the output of the module we would like to have also the specific model for the subject who performed the experiment.

**Comment by MartaLorenzini** [comment]
I've added the RFmodule I've written (xsens-tf-bridge) to the architecture. It allows to publish Xsens segments frames on RViz, the ROS 3D visualizer. To publish the force plates and the iCub frames we are planning to employ already existing yarp modules. 

![scheme](https://cloud.githubusercontent.com/assets/14000127/23759623/95faced4-04ed-11e7-8705-f604fe64b100.png)

**Comment by francesco-romano** [comment]
Done by ddfb721c59efacf942b0556e1cfcf42d7f44b3ed

**Comment by traversaro** [comment]
Top! 👍
